---
- name: Provisioning Server
  hosts: all
  become: yes
  tasks:
    - name: Install NTP on CentOS
      yum:
        name: "{{item}}"
        state: present
      when: ansible_distribution =="CentOS"
      loop:
        - ntp
        - wget
        - git
        - zip
        - unzip
   
    - name: Install NTP on Ubuntu 
      apt:
         name: "{{item}}"
         state: present
         update_cache: yes
      when: ansible_distribution =="Ubuntu"
      loop:
        - ntp
        - wget
        - git
        - zip
        - unzip

    - name: Start and enable NTP on Redhat
      service:
        name: ntpd
        state: started
        enabled: yes
      when: ansible_os_family == "RedHat"


    - name: Start and enable NTP on Debian
      service:
        name: ntp
        state: started
        enabled: yes
      when: ansible_os_family == "Debian"

    - name: Add group
      group:
        name: devops
        state: present

    - name: Add users
      user:
        name: "{{item}}"
        state: present
        groups: devops
      loop:
        - user1
        - user2
        - user3
        - user4
   
    - name: Banner file /etc/motd
      copy:
        content: "{{ansible_distribution}} is managed by Ansible.\n"
        dest: /etc/motd

    - name: Deploy NTP conf file for redhat
      template:
        src: ./templates/ntp_redhat.conf.j2
        dest: /etc/ntp.conf
      when: ansible_os_family == "RedHat"
      notify:
        - Restart NTP on Redhat

    - name: Deploy NTP conf file for debian
      template:
        src: ./templates/ntp_debian.conf.j2
        dest: /etc/ntp.conf
      when: ansible_os_family == "Debian"
      notify:
        - Restart NTP on Debian

    - name: Directory for dev data
      file:
        path: /opt/devdata
        state: directory
        mode: 0775
 
  handlers:
    - name: Restart NTP on Redhat
      service:
        name: ntpd
        state: restarted
        enabled: yes
      when: ansible_os_family == "RedHat"

    - name: Restart NTP on Debian
      service:
        name: ntp
        state: restarted
        enabled: yes
      when: ansible_os_family == "Debian"

   
