---
- name: Setup DBserver
  hosts: dbsrvgrp
  become: yes
  tasks:
  - name: install mariadb server
    yum: 
       name: mariadb-server
       state: present
  - name: install python mysql
    yum:
       name: MySQL-python
       state: present
  - name: start and enable mariadb
    service:
           name: mariadb
           state: started
           enabled: yes
  - name: create a db with name 'accounts'
    mysql_db:
            name: accounts
            state: present   
  - name: Create database user with name 'admin'
    mysql_user:
      name: admin
      password: 12345
      priv: '*.*:ALL'
      state: present
