---
- name: Setup DBserver
  hosts: dbgroup
  become: yes
  #  vars:
  #    dbname: groups
  #    dbuser: devops
  #    dbpass: admin123
  tasks:
  - debug:
          msg: "The value of dbuser is {{dbuser}}"
  - name: install mariadb server
    yum: 
       name: mariadb-server
       state: present
  - name: install python mysql
    yum:
       name: MySQL-python
       state: present
  - name: start and enable mariadb
    service:
           name: mariadb
           state: started
           enabled: yes
  - name: create a db with name 'accounts'
    mysql_db:
            name: "{{dbname}}"
            state: present   
  - name: Create database user with name 'admin'
    mysql_user:
      name: "{{dbuser}}"
      password: "{{dbpass}}"
      priv: '*.*:ALL'
      state: present
